// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0-devel
// 	protoc        v4.23.4
// source: log_registration.proto

package log_registration_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogAppRegistrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId           string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppUnixPipePath string `protobuf:"bytes,2,opt,name=app_unix_pipe_path,json=appUnixPipePath,proto3" json:"app_unix_pipe_path,omitempty"`
}

func (x *LogAppRegistrationResponse) Reset() {
	*x = LogAppRegistrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_registration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogAppRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAppRegistrationResponse) ProtoMessage() {}

func (x *LogAppRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_registration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAppRegistrationResponse.ProtoReflect.Descriptor instead.
func (*LogAppRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_log_registration_proto_rawDescGZIP(), []int{0}
}

func (x *LogAppRegistrationResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *LogAppRegistrationResponse) GetAppUnixPipePath() string {
	if x != nil {
		return x.AppUnixPipePath
	}
	return ""
}

var File_log_registration_proto protoreflect.FileDescriptor

var file_log_registration_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x6f, 0x67, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x62, 0x72, 0x70, 0x63, 0x5f, 0x6c,
	0x6f, 0x67, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x1a,
	0x4c, 0x6f, 0x67, 0x41, 0x70, 0x70, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x2b, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x70, 0x69,
	0x70, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61,
	0x70, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x50, 0x69, 0x70, 0x65, 0x50, 0x61, 0x74, 0x68, 0x32, 0x74,
	0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x41, 0x70, 0x70, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x31, 0x2e, 0x62, 0x72, 0x70, 0x63, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x6c, 0x6f, 0x67, 0x5f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_registration_proto_rawDescOnce sync.Once
	file_log_registration_proto_rawDescData = file_log_registration_proto_rawDesc
)

func file_log_registration_proto_rawDescGZIP() []byte {
	file_log_registration_proto_rawDescOnce.Do(func() {
		file_log_registration_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_registration_proto_rawDescData)
	})
	return file_log_registration_proto_rawDescData
}

var file_log_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_log_registration_proto_goTypes = []interface{}{
	(*LogAppRegistrationResponse)(nil), // 0: brpc_log_registration.LogAppRegistrationResponse
	(*emptypb.Empty)(nil),              // 1: google.protobuf.Empty
}
var file_log_registration_proto_depIdxs = []int32{
	1, // 0: brpc_log_registration.RegistrationService.RegisterLogApp:input_type -> google.protobuf.Empty
	0, // 1: brpc_log_registration.RegistrationService.RegisterLogApp:output_type -> brpc_log_registration.LogAppRegistrationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_log_registration_proto_init() }
func file_log_registration_proto_init() {
	if File_log_registration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_log_registration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogAppRegistrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_registration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_registration_proto_goTypes,
		DependencyIndexes: file_log_registration_proto_depIdxs,
		MessageInfos:      file_log_registration_proto_msgTypes,
	}.Build()
	File_log_registration_proto = out.File
	file_log_registration_proto_rawDesc = nil
	file_log_registration_proto_goTypes = nil
	file_log_registration_proto_depIdxs = nil
}
